import { AchievementName } from './enum';

export const achievements = [
  { name: AchievementName.Book1000Pages, title: 'Book 1000 Pages', image: '' },
  { name: AchievementName.Read100Books, title: 'Read 100 Books', image: '' },
  { name: AchievementName.Read150Books, title: 'Read 150 Books', image: '' },
  { name: AchievementName.Read15Books, title: 'Read 15 Books', image: '' },
  { name: AchievementName.Read10Books, title: 'Read 10 Books', image: '' },
  { name: AchievementName.Read1Books, title: 'Read 1 Books', image: '' },
  { name: AchievementName.Read200Books, title: 'Read 200 Books', image: '' },
  { name: AchievementName.Read20Books, title: 'Read 20 Books', image: '' },
  { name: AchievementName.Read25Books, title: 'Read 25 Books', image: '' },
  { name: AchievementName.Read30Books, title: 'Read 30 Books', image: '' },
  { name: AchievementName.Read35Books, title: 'Read 35 Books', image: '' },
  { name: AchievementName.Read3Books, title: 'Read 3 Books', image: '' },
  { name: AchievementName.Read40Books, title: 'Read 40 Books', image: '' },
  { name: AchievementName.Read45Books, title: 'Read 45 Books', image: '' },
  { name: AchievementName.Read50Books, title: 'Read 50 Books', image: '' },
  { name: AchievementName.Read55Books, title: 'Read 55 Books', image: '' },
  { name: AchievementName.Read5Books, title: 'Read 5 Books', image: '' },
  { name: AchievementName.Read60Books, title: 'Read 60 Books', image: '' },
  { name: AchievementName.Read65Books, title: 'Read 65 Books', image: '' },
  { name: AchievementName.Read70Books, title: 'Read 70 Books', image: '' },
  { name: AchievementName.Read75Books, title: 'Read 75 Books', image: '' },
  { name: AchievementName.Read80Books, title: 'Read 80 Books', image: '' },
  { name: AchievementName.Read85Books, title: 'Read 85 Books', image: '' },
  { name: AchievementName.Read90Books, title: 'Read 90 Books', image: '' },
  { name: AchievementName.Read95Books, title: 'Read 95 Books', image: '' },
  {
    name: AchievementName.ThreeBooksByOneAuthor,
    title: '3 Books by One Author',
    image: '',
  },
  {
    name: AchievementName.ThreeBooksOfOneGenre,
    title: '3 Books of One Genre',
    image: '',
  },
  {
    name: AchievementName.ThreeHorrorBooks,
    title: '3 Horror Books',
    image: '',
  },
  {
    name: AchievementName.BookInTheLibrary,
    title: 'Book in the Library',
    image: '',
  },
  { name: AchievementName.Audiobook, title: 'Audiobook', image: '' },
  { name: AchievementName.BookAtHome, title: 'Book at Home', image: '' },
  { name: AchievementName.BookAtWork, title: 'Book at Work', image: '' },
  {
    name: AchievementName.BookReadInOneDay,
    title: 'Book Read in One Day',
    image: '',
  },
  { name: AchievementName.BookInACafe, title: 'Book in a Cafe', image: '' },
  {
    name: AchievementName.BookInEducationInstitution,
    title: 'Book in Education Institution',
    image: '',
  },
  { name: AchievementName.BookInNature, title: 'Book in Nature', image: '' },
  {
    name: AchievementName.BookInTransport,
    title: 'Book in Transport',
    image: '',
  },
  { name: AchievementName.BookOnTheRoad, title: 'Book on the Road', image: '' },
  { name: AchievementName.EBook, title: 'E-book', image: '' },
  { name: AchievementName.FriendBook, title: 'Friend’s Book', image: '' },
  {
    name: AchievementName.ReadNonStopThirtyDays,
    title: 'Read Non-stop 30 Days',
    image: '',
  },
];
