export const genres = [
  'Fantasy',
  'Science',
  'Dystopian',
  'Action & Adventure',
  'Romance',
  'Mystery',
  'Horror',
  'Thriller',
  'Paranormal',
  'Western',
  'Literary',
  'Historical',
  'Contemporary',
  'Magic Realism',
  'Graphic Novel',
  'Short Story',
  'Young Adult',
  'New Adult',
  'Children’s',
  'Classics',
  'Gothic',
  'Satire',
  'Literary Criticism',
  'Mythology & Folklore',
  'Women`s',
  'Military',
  'Slice of Life',
  'Crime',
  'Experimental',
  'Manga',
  'Religious',
  'Anime',
  'Comedy',
  'Drama',
  'Espionage',
  'Fairy Tale',
  'Picaresque',
  'Political',
  'Swashbuckler',
  'Urban Fantasy',
  'War',
  'Western',
  'Alternate History',
  'bildungsroman',
  'Epistolary',
  'Novel',
  'epic',
  'Other',
  'Biographies',
  'Memoirs & Autobiographies',
  'Food & Drink',
  'Art & Photography',
  'Self-Help & Motivational',
  'History',
  'Crafts',
  'Hobbies & Home',
  'Humor & Entertainment',
  'Business & Economics',
  'Law & Criminology',
  'Politics & Social Sciences',
  'Religion & Spirituality',
  'Education & Teaching',
  'Travel',
  'True Crime',
  'Poetry',
  'Science & Technology',
  'Health & Medicine',
  'Philosophy',
  'Sports & Recreation',
  'Nature & Environment',
  'Reference (dictionaries, encyclopedias, etc.)',
  'Academic/Scholarly Works',
  'Journalism & Essays',
  'Career Development & Professional Growth',
  'Cultural Studies',
  'Parenting & Family',
  'Cookbook',
  'Psychology',
  'Anthropology',
  'Ethnography',
  'Architecture & Design',
  'Finance',
  `DIY & How-To`,
  'Agriculture & Farming',
];
